version: '3'
services:
  app:
    container_name: pic_pay_app
    restart: always
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - '80:3000'
    links:
      - 'db'
    depends_on:
      - 'db'
    environment:
      - MYSQL_HOST=db
      - MYSQL_USERNAME=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT}
      - WAIT_HOSTS=db:3306
  db:
    build: ./docker/db
    image: mysql:latest
    container_name: pic_pay_db
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    expose:
      - '3306'
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    security_opt:
      - seccomp:unconfined
