version: '3'
services:
  app:
    container_name: pic_pay_app
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - 'db'
  db:
    image: mysql:8.0.20
    container_name: pic_pay_db
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    expose:
      - '3306'
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}